language: node_js
node_js:
- node

services:
- xvfb

cache:
  npm: false
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron

install:
- npm ci

jobs:
  include:
    - stage: test
      os: linux
      script: &test-script
      - npm run bundle:dev
      - npm test
    - stage: test
      os: osx
      script: *test-script
    - stage: build
      os: linux
      script: &build-script
      - npm run build
    - stage: build
      os: osx
      script: *build-script
    - stage: deploy
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        file_glob: true
        file:
          - 'dist/*.dmg'
          - 'dist/*.dmg.blockmap'
          - 'dist/latest-mac.yml'
        overwrite: true
        draft: true
        on:
          all_branches: true
