language: node_js
node_js:
- node

os:
- osx
- linux

services:
- xvfb

cache:
  npm: false
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron

env:
- build_command=build
- build_command=publish

install:
- npm ci

jobs:
  include:
    - if: branch = master
      env: build_command=publish
    - if: NOT branch = master
      env: build_command=build
  exclude:
    - if: branch = master
      env: build_command=build
    - if: NOT branch = master
      env: build_command=publish

script:
- npm run bundle:prod
- npm test
- npm run build

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "dist/*"
  skip_cleanup: true
  draft: true
