language: node_js
node_js:
- node

os:
- osx
- linux

services:
- xvfb

cache:
  npm: false
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron

install:
- npm ci

script:
- npm run bundle:prod
- npm test
- npm run build
