language: node_js
node_js:
- node

os:
- osx
- linux

services:
- xvfb

cache:
  npm: false
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron

install:
- npm ci

jobs:
  include:
    - script:
      - npm run bundle:dev
      - npm test
    - stage: build
      script: npm run build
    - stage: deploy
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        file_glob: true
        file:
          - 'dist/*.dmg'
          - 'dist/*.dmg.blockmap'
          - 'dist/latest-mac.yml'
        overwrite: true
        draft: true
        on:
          all_branches: true
