language: node_js
node_js:
- node

os:
- osx
- linux

services:
- xvfb

cache:
  npm: false
  directories:
  - $HOME/.npm
  - $HOME/.cache/electron
  - $HOME/Library/Caches/electron

env:
- build_command=build
- build_command=publish

install:
- npm ci

jobs:
  include:
    - if: branch = master
      env: build_command=publish
  exclude:
    - if: branch = master
      env: build_command=build

script:
- npm run bundle:prod
- npm test
- npm run $build_command
