language: node_js
node_js:
- node

os:
- osx
- linux

jobs:
  include:
  - os: linux
    services:
    - xvfb
    script:
    - xvfb-run npm test
  - os: osx
    script:
    - npm test

install:
- npm ci
- npm run bundle:prod
