environment:
  GH_TOKEN:
    secure: QFxUKBUe3jwvUdS2rPo4w8J+WBaui0d0brYgm1yfgPU/h6jMpPqlGAJP6cH94yrp
  nodejs_version: "12"

version: 0.0.0.{build}

cache:
- '%LOCALAPPDATA%/electron/cache'
- '%LOCALAPPDATA%/electron-builder/cache'

install:
- ps: Install-Product node $env:nodejs_version
- cmd: node --version
- cmd: npm --version
- cmd: npm ci

build: off

for:
-
  branches:
    only:
     - master

  test_script:
  - cmd: npm run build
  - cmd: npm test

  on_success:
  - cmd: npm run publish

-
  branches:
    except:
      - master

  test_script:
  - cmd: npm run build
  - cmd: npm test

artifacts:
  - path: dist/*.exe
    name: Installer

  - path: dist/*.exe.blockmap
    name: Installer blockmap

  - path: dist/latest.yml
    name: Update file

deploy:
  release: Draft
  provider: GitHub
  auth_token: $(GH_TOKEN)
  draft: true
  prerelease: true
  force_update: true
