environment:
  nodejs_version: "12"

version: 1.0.{build}

install:
- ps: Install-Product node $env:nodejs_version
- cmd: node --version
- cmd: npm --version
- cmd: npm install

build_script:
- cmd: npm run build

test_script:
- cmd: npm test

